package com.henryai.aviationwatch.data

import android.content.Context
import com.henryai.aviationwatch.core.Airport
import com.henryai.aviationwatch.core.AirportCsv
import com.henryai.aviationwatch.core.AirportDetailsCsv
import com.henryai.aviationwatch.core.Frequency
import com.henryai.aviationwatch.core.Runway
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.IOException

/** Airport, runways and frequencies for the airport info page. */
data class AirportInfo(
    val airport: Airport,
    val runways: List<Runway>,
    val frequencies: List<Frequency>,
)

/**
 * The bundled OurAirports database (`assets/airports.csv`, `runways.csv`,
 * `frequencies.csv`, generated by tools/build_airports.py). Airports are parsed
 * once and kept in memory; runways and frequencies are read per airport on demand.
 */
object AirportRepository {
    private const val AIRPORTS = "airports.csv"
    private const val RUNWAYS = "runways.csv"
    private const val FREQUENCIES = "frequencies.csv"
    private val mutex = Mutex()

    @Volatile
    private var cache: List<Airport>? = null

    /** All airports; empty if the APK was built without the database. */
    suspend fun airports(context: Context): List<Airport> =
        cache ?: mutex.withLock {
            cache ?: withContext(Dispatchers.IO) {
                readAsset(context, AIRPORTS) { AirportCsv.parse(it) }.orEmpty()
            }.also { cache = it }
        }

    /** Airport with runways and frequencies, or null if [ident] is unknown. */
    suspend fun info(context: Context, ident: String): AirportInfo? {
        val airport = airports(context).firstOrNull { it.ident == ident } ?: return null
        return withContext(Dispatchers.IO) {
            AirportInfo(
                airport = airport,
                runways = readAsset(context, RUNWAYS) { AirportDetailsCsv.runwaysFor(ident, it) }.orEmpty(),
                frequencies = readAsset(context, FREQUENCIES) {
                    AirportDetailsCsv.frequenciesFor(ident, it)
                }.orEmpty(),
            )
        }
    }

    private fun <T> readAsset(context: Context, name: String, parse: (Sequence<String>) -> T): T? = try {
        context.applicationContext.assets.open(name).bufferedReader().useLines(parse)
    } catch (e: IOException) {
        null
    }
}
