package com.henryai.aviationwatch.data

import android.content.Context
import com.henryai.aviationwatch.core.Airport
import com.henryai.aviationwatch.core.AirportCsv
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import java.io.IOException

/**
 * The bundled OurAirports database (`assets/airports.csv`, generated by
 * tools/build_airports.py). Parsed once on first use and kept in memory.
 */
object AirportRepository {
    private const val ASSET = "airports.csv"
    private val mutex = Mutex()

    @Volatile
    private var cache: List<Airport>? = null

    /** All airports; empty if the APK was built without the database. */
    suspend fun airports(context: Context): List<Airport> =
        cache ?: mutex.withLock {
            cache ?: withContext(Dispatchers.IO) { load(context.applicationContext) }
                .also { cache = it }
        }

    private fun load(context: Context): List<Airport> = try {
        context.assets.open(ASSET).bufferedReader().useLines { AirportCsv.parse(it) }
    } catch (e: IOException) {
        emptyList()
    }
}
